const express = require('express')
const router = express.Router()
const authenticateToken = require('../../middlewares/auth/adminAuth')

// Routes
// Category routes
router.post('/user/signup', require('./controllers/adminSignup'))
router.post('/user/login', require('./controllers/adminLogin'))
router.patch('/user/resetPwd', authenticateToken, require('./controllers/resetPwd'))
router.get('/user/detailsList', authenticateToken, require('./controllers/getUserDetailsList'))
router.get('/user/getDetail/:userId', authenticateToken, require('./controllers/getDetail'))
router.get('/user/celebrityList', authenticateToken, require('./controllers/getUserCelebrityList'))
router.patch('/user/evaluationCelebrity', authenticateToken, require('./controllers/updateCelebrityStatus'))
router.get('/category/list', authenticateToken, require('./controllers/getCategoryForAdmin'))
router.get('/category/:categoryId', authenticateToken, require('./controllers/getCategoryDetailsById'))
router.post('/category/addCategory', authenticateToken, require('./controllers/addCategoryForAdmin'))
router.put('/category/editCategory', authenticateToken, require('./controllers/updateCategoryForAdmin'))
router.delete('/category/deleteCategory/:categoryId', authenticateToken, require('./controllers/deleteCategoryForAdmin'))
router.put('/category/uploadImage', authenticateToken, require('./controllers/uploadImage'))
router.put('/subscription/uploadImage', authenticateToken, require('./controllers/uploadSubscriptionImage'))
router.post('/subscription/addSubscription', authenticateToken, require('./controllers/addSubscription'))
router.put('/subscription/editSubscription', authenticateToken, require('./controllers/editSubscription'))
router.get('/subscription/getSubscriptionList', authenticateToken, require('./controllers/getSubscriptionList'))
router.get('/subscription/:planId', authenticateToken, require('./controllers/getSubscriptionById'))
router.delete('/subscription/deactive/:planId/:isActive', authenticateToken, require('./controllers/deleteSubscription'))
router.post('/language/addLanguage', authenticateToken, require('./controllers/addLanguage'))
router.put('/language/editLanguage', authenticateToken, require('./controllers/editLanguage'))
router.get('/language/getLanguageList', authenticateToken, require('./controllers/getLanguageList'))
router.get('/language/:languageId', authenticateToken, require('./controllers/getLanguageById'))
router.delete('/language/deleteLanguage/:languageId', authenticateToken, require('./controllers/deleteLanguage'))
router.post('/setting/setApplePayStatus', authenticateToken, require('./controllers/applePaySetting'))
router.get('/getSetting', authenticateToken, require('./controllers/getSetting'))

module.exports = router
